/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  pythonSidebar: [{type: 'autogenerated', dirName: 'python'}],
  personalWebsiteSidebar: [{type: 'autogenerated', dirName: 'personal-website'}],
  newPersonalWebsiteSidebar: [{type: 'autogenerated', dirName: 'new-personal-website'}],
  chemistryGuideSidebar: [{type: 'autogenerated', dirName: 'chemistry-guide'}],
  shpeathonSidebar: [{type: 'autogenerated', dirName: 'shpeathon'}],
  adminSidebar: [{type: 'autogenerated', dirName: 'transfer-of-knowledge'}],

};
